# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 15:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('flowcell_id', models.CharField(blank=True, max_length=200)),
                ('ftp_url', models.CharField(blank=True, max_length=200)),
                ('batch_id', models.CharField(blank=True, max_length=200)),
                ('platform', models.CharField(blank=True, max_length=200)),
                ('java_path', models.CharField(blank=True, max_length=200)),
                ('bwa_path', models.CharField(blank=True, max_length=200)),
                ('picard_path', models.CharField(blank=True, max_length=200)),
                ('gatk_path', models.CharField(blank=True, max_length=200)),
                ('gatk_version', models.CharField(blank=True, max_length=200)),
                ('reference_path', models.CharField(blank=True, max_length=200)),
                ('known_indels_path', models.CharField(blank=True, max_length=200)),
                ('common_variants_nkmi_path', models.CharField(blank=True, max_length=200)),
                ('common_artefacts_path', models.CharField(blank=True, max_length=200)),
                ('dbsnp_path', models.CharField(blank=True, max_length=200)),
                ('alamut_path', models.CharField(blank=True, max_length=200)),
                ('sample_list_path', models.CharField(blank=True, max_length=200)),
                ('sample_list', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Ngs_test',
            fields=[
                ('Ngs_test_primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('capture_method', models.CharField(blank=True, max_length=200)),
                ('capture_version', models.CharField(blank=True, max_length=200)),
                ('virtual_panel_phenotype', models.CharField(blank=True, max_length=200)),
                ('virtual_panel_genes_and_transcript', django.contrib.postgres.fields.jsonb.JSONField()),
                ('date_of_analysis', models.CharField(blank=True, max_length=200)),
                ('covered_interval_list_by_phenotype', django.contrib.postgres.fields.jsonb.JSONField()),
                ('variant_calling_intervals', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('sample_primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('bam_file_path', models.CharField(blank=True, max_length=200)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClinSci.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='Sample_metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_metrics_path', models.CharField(blank=True, max_length=200)),
                ('phenotype_metrics_path', models.CharField(blank=True, max_length=200)),
                ('overall_pct_target_bases_20x', models.CharField(blank=True, max_length=200)),
                ('overall_pct_target_bases_30x', models.CharField(blank=True, max_length=200)),
                ('phen_pct_target_bases_20x', models.CharField(blank=True, max_length=200)),
                ('phen_pct_target_bases_30x', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='ngs_test',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClinSci.Sample'),
        ),
    ]
