# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinSci', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sample_metrics',
            new_name='Ngs_test_metrics',
        ),
        migrations.RenameField(
            model_name='ngs_test',
            old_name='virtual_panel_phenotype',
            new_name='capture_profile',
        ),
        migrations.AddField(
            model_name='sample',
            name='capture_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='sample',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sample',
            name='ex_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sample',
            name='gender',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sample',
            name='mody_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RemoveField(
            model_name='sample',
            name='batch',
        ),
        migrations.AddField(
            model_name='sample',
            name='batch',
            field=models.ManyToManyField(to='ClinSci.Batch'),
        ),
    ]
